# Generated by Django 4.1.2 on 2022-11-01 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import questionic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_profile', models.ImageField(blank=True, upload_to=questionic.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=1024)),
                ('date_answered', models.DateTimeField(auto_now_add=True, verbose_name='Date Answered')),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionic.account')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('detail', models.CharField(max_length=1024)),
                ('category', models.CharField(max_length=64)),
                ('grade', models.CharField(max_length=64)),
                ('date_asked', models.DateTimeField(auto_now_add=True, verbose_name='Date Asked')),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionic.account')),
                ('reporter', models.ManyToManyField(blank=True, related_name='question_report', to='questionic.account')),
            ],
        ),
        migrations.CreateModel(
            name='ReplyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=1024)),
                ('date_reply_answered', models.DateTimeField(auto_now_add=True, verbose_name='Date Reply Answered')),
                ('from_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionic.answer')),
                ('reply_answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionic.account')),
                ('reporter', models.ManyToManyField(blank=True, related_name='reply_report', to='questionic.account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReplyAnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=questionic.models.reply_answer_directory_path)),
                ('reply_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='questionic.replyanswer')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=questionic.models.question_directory_path)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='questionic.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='questionic.tag'),
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to=questionic.models.answer_directory_path)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='questionic.answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='from_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionic.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='reporter',
            field=models.ManyToManyField(blank=True, related_name='answer_report', to='questionic.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='fav_tag',
            field=models.ManyToManyField(blank=True, related_name='fav_tag', to='questionic.tag'),
        ),
        migrations.AddField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to='questionic.account'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
