# Generated by Django 4.1.2 on 2022-11-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fav_question',
            field=models.ManyToManyField(blank=True, related_name='fav_question', to='questionic.tag'),
        ),
        migrations.AddField(
            model_name='account',
            name='report',
            field=models.ManyToManyField(blank=True, related_name='reporter', to='questionic.account'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_notification_count', models.PositiveIntegerField(default=0)),
                ('reply_notification_count', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='questionic.account')),
                ('follow_notification', models.ManyToManyField(blank=True, related_name='noti_follow', to='questionic.question')),
                ('reply_notification', models.ManyToManyField(blank=True, related_name='noti_reply', to='questionic.answer')),
            ],
        ),
    ]
